# Generated by Django 3.2.9 on 2021-11-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0006_auto_20211128_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='clicks.location'),
        ),
    ]
