# Generated by Django 3.2.9 on 2021-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0007_image_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
