# Generated by Django 3.2.9 on 2021-11-30 08:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0012_remove_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
