# Generated by Django 3.2.9 on 2021-11-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0013_auto_20211130_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
