# Generated by Django 3.2.9 on 2021-11-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicks', '0015_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
